# Generated by Django 5.0.6 on 2024-08-02 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ux', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
